backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Twitter Card", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}
  - name: "Nodes"
    label: "Nodes"
    folder: "_nodes"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Color"
        name: "color"
        widget: "select"
        default: "#bdc3c7"
        options:
          - { label: "Turquoise", value: "#1abc9c" }
          - { label: "Emerald", value: "#2ecc71" }
          - { label: "Peter river", value: "#3498db" }
          - { label: "Amethyst", value: "#9b59b6" }
          - { label: "Wet asphalt", value: "#34495e" }
          - { label: "Sun flower", value: "#f1c40f" }
          - { label: "Carrot", value: "#e67e22" }
          - { label: "Alizarin", value: "#e74c3c" }
          - { label: "Cloud", value: "#ecf0f1" }
          - { label: "Amethyst", value: "#9b59b6" }
          - { label: "Silver", value: "#bdc3c7" }
          - { label: "Asbestos", value: "#7f8c8d" }
  - name: "Edges"
    label: "Edges"
    folder: "_edges"
    create: true
    identifier_field: from
    fields:
      - label: "From"
        name: "from"
        widget: relation
        collection: "Nodes"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "To"
        name: "to"
        widget: relation
        collection: "Nodes"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Arrow"
        name: "arrow"
        widget: boolean
        required: false
  - name: "Podcasts"
    label: "Podcasts"
    label_single: "Podcast"
    folder: "_podcasts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: string
        hint: "Épisode N"
      - label: "Subtitle"
        name: "subtitle"
        widget: string
      - label: "Date"
        name: "date"
        default: ""
        widget: date
        format: 'DD/MM/YYYY'
      - label: "Duration"
        name: "duration"
        widget: string
        hint: "HH:mm:ii"
      - label: "Resume"
        name: "resume"
        widget: text
      - label: "Description"
        name: "description"
        widget: markdown
      - label: "MP3"
        name: "mp3"
        widget: file
        allow_multiple: false
      - label: "Thumbnail"
        name: "thumbnail"
        widget: image
        allow_multiple: false
        hint: "1900x1260"
      - label: User
        name: user
        widget: relation
        collection: Users
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
  - name: "Users"
    label: "Users"
    label_single: "User"
    folder: "_users"
    create: true
    fields:
      - label: "Name"
        name: "title"
        widget: string
      - label: "Description"
        name: "description"
        widget: text
      - label: "Avatar"
        name: "avatar"
        widget: image
        allow_multiple: false
      - label: "Links"
        name: "links"
        widget: list
        fields:
          - label: Icon
            name: icon
            widget: string
          - label: URL
            name: url
            widget: string
